### PR TITLE
Change repo references from "bamboo" to "boo-lang"

### PR DESCRIPTION
**Pull request by eatdrinksleepcode**

### CODE REVIEW

**Comment by masonwheeler** [comment]
@andyhasit  I would approve this, but I don't have access.  Can you handle this one?

**Comment by masonwheeler** [comment]
@andyhasit Thanks! BTW can you look at https://github.com/boo-lang/boo/issues/170, https://github.com/boo-lang/boo/issues/171 and https://github.com/boo-lang/boo/issues/172?  They were filed under Boo but they pertain to this site.  It looks like we've got some bitrot problems going on over here...

**Comment by andyhasit** [comment]
Those are all relating to http://boo-lang.org/ which is not from http://boo-language.github.io/ 
I'm not sure who runs that...

**Comment by masonwheeler** [comment]
Good point.  But at least the code converter part seems identical; there's the same broken link to the online converter on this site.

**Comment by andyhasit** [comment]
The code converter linked to on  http://boo-language.github.io/ is provided by sharpdevelop, and the page is unresponsive, although I don't know if this is temporary.

The code interpreter on http://boo-lang.org/ is provided by http://tryboo.pollinimini.net/ and that too seems broken. 

The boo-language repo has no control over any of the above, except for removing the link to the converter, or finding something we can point it to.

**Pull request merged**
